[dependencies]
rand = "0.8.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ureq = { version = "2.0.2", features = ["json"] }

[package]
authors = ["sms77 e.K. <support@sms77.io>"]
categories = ["api-bindings", "web-programming"]
description = "Official API client for Sms77.io SMS Gateway."
edition = "2018"
homepage = "https://github.com/sms77io/rust"
keywords = ["cnam", "hlr", "mnp", "sms", "tts"]
license-file = "LICENSE"
name = "sms77-client"
readme = "README.md"
repository = "https://github.com/sms77io/rust.git"
version = "0.1.0"